<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.4" tiledversion="1.4.3" name="hero2" tilewidth="50" tileheight="37" tilecount="112" columns="7">
 <image source="Adventurer-1.5/adventurer-v1.5-Sheet.png" width="385" height="592"/>
 <tile id="0" type="idle"/>
 <tile id="1" type="idle"/>
 <tile id="2" type="idle"/>
 <tile id="3" type="idle"/>
 <tile id="4" type="crouch"/>
 <tile id="5" type="crouch"/>
 <tile id="6" type="crouch"/>
 <tile id="7" type="crouch"/>
 <tile id="8" type="run"/>
 <tile id="9" type="run"/>
 <tile id="10" type="run"/>
 <tile id="11" type="run"/>
 <tile id="12" type="run"/>
 <tile id="13" type="run"/>
 <tile id="14" type="takla"/>
 <tile id="15" type="takla"/>
 <tile id="16" type="takla"/>
 <tile id="17" type="takla"/>
 <tile id="18" type="takla"/>
 <tile id="19" type="takla"/>
 <tile id="20" type="takla"/>
 <tile id="21" type="takla"/>
 <tile id="22" type="takla"/>
 <tile id="23" type="takla"/>
 <tile id="24" type="tackle"/>
 <tile id="25" type="tackle"/>
 <tile id="26" type="tackle"/>
 <tile id="27" type="tackle"/>
 <tile id="28" type="tackle"/>
 <tile id="29" type="hang"/>
 <tile id="30" type="hang"/>
 <tile id="31" type="hang"/>
 <tile id="32" type="hang"/>
 <tile id="33" type="climb"/>
 <tile id="34" type="climb"/>
 <tile id="35" type="climb"/>
 <tile id="36" type="climb"/>
 <tile id="37" type="climb"/>
 <tile id="38" type="idle2"/>
 <tile id="39" type="idle2"/>
 <tile id="40" type="idle2"/>
 <tile id="41" type="idle2"/>
 <tile id="42" type="attack1"/>
 <tile id="43" type="attack1"/>
 <tile id="44" type="attack1"/>
 <tile id="45" type="attack1"/>
 <tile id="46" type="attack1"/>
 <tile id="47" type="attack2"/>
 <tile id="48" type="attack2"/>
 <tile id="49" type="attack2"/>
 <tile id="50" type="attack2"/>
 <tile id="51" type="attack2"/>
 <tile id="52" type="attack2"/>
 <tile id="53" type="attack3"/>
 <tile id="54" type="attack3"/>
 <tile id="55" type="attack3"/>
 <tile id="56" type="attack3"/>
 <tile id="57" type="attack3"/>
 <tile id="58" type="attack3"/>
 <tile id="59" type="hurt"/>
 <tile id="60" type="hurt"/>
 <tile id="61" type="hurt"/>
 <tile id="62" type="die"/>
 <tile id="63" type="die"/>
 <tile id="64" type="die"/>
 <tile id="65" type="die"/>
 <tile id="66" type="die"/>
 <tile id="67" type="die"/>
 <tile id="68" type="die"/>
 <tile id="69" type="draw"/>
 <tile id="70" type="draw"/>
 <tile id="71" type="draw"/>
 <tile id="72" type="draw"/>
 <tile id="73" type="ensheathe"/>
 <tile id="74" type="ensheathe"/>
 <tile id="75" type="ensheathe"/>
 <tile id="76" type="ensheathe"/>
 <tile id="77" type="jump"/>
 <tile id="78" type="jump"/>
 <tile id="79" type="slide"/>
 <tile id="80" type="slide"/>
 <tile id="81" type="ladderclimb"/>
 <tile id="82" type="ladderclimb"/>
 <tile id="83" type="ladderclimb"/>
 <tile id="84" type="ladderclimb"/>
 <tile id="85" type="items"/>
 <tile id="86" type="items"/>
 <tile id="87" type="items"/>
 <tile id="88" type="stop"/>
 <tile id="89" type="stop"/>
 <tile id="90" type="stop"/>
 <tile id="91" type="stop"/>
 <tile id="92" type="stop"/>
 <tile id="93" type="comboattack"/>
 <tile id="94" type="comboattack"/>
 <tile id="95" type="comboattack"/>
 <tile id="96" type="comboattack"/>
 <tile id="97" type="comboattack"/>
 <tile id="98" type="comboattack"/>
 <tile id="99" type="comboattack"/>
 <tile id="100" type="comboattack"/>
 <tile id="101" type="comboattack"/>
 <tile id="102" type="comboattack"/>
 <tile id="103" type="comboattack"/>
 <tile id="104" type="comboattack"/>
 <tile id="105" type="comboattack"/>
 <tile id="106" type="comboattack"/>
 <tile id="107" type="comboattack"/>
 <tile id="108" type="comboattack"/>
</tileset>
